[licenses]
confidence-threshold = 0.93
allow = [
    "MIT-0", "MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception",
    "ISC", "0BSD", "BSD-2-Clause", "BSD-3-Clause", "OpenSSL",
    "Unicode-3.0", "BSL-1.0", "MPL-2.0", "CDLA-Permissive-2.0",
    "Zlib", "NCSA", "LGPL-3.0", "CC0-1.0", "Unicode-DFS-2016"
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
deny = [
    { name = "native-tls" },
    { name = "openssl-sys" }
]
